# Here is detailed GitHub link for detailed cities
# https://github.com/joelacus/world-cities

# Here is the detailed list of cities in JSON file
# https://raw.githubusercontent.com/lutangar/cities.json/master/cities.json
# I have saved also in Google Drive folder, here is the link:
# https://drive.google.com/drive/folders/1qMXBbKkE32xyIKdEjVO6aN9hHn0VVFm9

# List of Major Cities
major_cities = [
    "Abuja", "Accra", "Addis Ababa", "Ahmedabad", "Aleppo", "Alexandria", "Algiers", "Almaty", "Amman",
    "Amsterdam", "Anchorage", "Ankara", "Antananarivo", "Apia", "Arnold", "Ashgabat", "Asmara", "Asuncion",
    "Athens", "Auckland", "Baghdad", "Baku", "Bamako", "Banda Aceh", "Bandar Seri Begawan", "Bangkok",
    "Bangui", "Banjul", "Barcelona", "Barranquilla", "Basrah", "Basse-Terre", "Basseterre", "Beijing",
    "Beirut", "Bekasi", "Belem", "Belgrade", "Belmopan", "Belo Horizonte", "Bengaluru", "Berlin", "Bern",
    "Bishkek", "Bissau", "Bogota", "Brasilia", "Bratislava", "Brazzaville", "Bridgetown", "Brisbane",
    "Brussels", "Bucharest", "Budapest", "Buenos Aires", "Bujumbura", "Bursa", "Busan", "Cairo", "Cali",
    "Caloocan", "Camayenne", "Canberra", "Cape Town", "Caracas", "Casablanca", "Castries", "Cayenne",
    "Charlotte Amalie", "Chengdu", "Chennai", "Chicago", "Chisinau", "Chongqing", "Christchurch", "Clermont-Ferrand",
    "Colombo", "Conakry", "Copenhagen", "Cordoba", "Curitiba", "Dakar", "Dallas", "Damascus", "Dar es Salaam",
    "Darwin", "Davao City", "Delhi", "Dhaka", "Dili", "Djibouti", "Doha", "Dongguan", "Douala", "Dubai",
    "Dublin", "Durban", "Dushanbe", "Ekurhuleni", "Faisalabad", "Fort-de-France", "Fortaleza", "Freetown",
    "Fukuoka", "Funafuti", "Gaborone", "George Town", "Georgetown", "Gibraltar", "Gitega", "Giza", "Guadalajara",
    "Guangzhou", "Guatemala City", "Guayaquil", "Gujranwala", "Gustavia", "Gwangju", "Hamburg", "Hanoi",
    "Harare", "Havana", "Helsinki", "Ho Chi Minh City", "Hobart", "Hong Kong", "Honiara", "Honolulu", "Houston",
    "Hyderabad", "Ibadan", "Incheon", "Isfahan", "Islamabad", "Istanbul", "Izmir", "Jaipur", "Jakarta",
    "Jeddah", "Jerusalem", "Johannesburg", "Juarez", "Juba", "Kabul", "Kaduna", "Kampala", "Kano", "Kanpur",
    "Karachi", "Karaj", "Kathmandu", "Kawasaki", "Kharkiv", "Khartoum", "Khulna", "Kigali", "Kingsburg",
    "Kingston", "Kingstown", "Kinshasa", "Kobe", "Kolkata", "Kota Bharu", "Kowloon", "Kuala Lumpur", "Kumasi",
    "Kuwait", "Kyiv", "Kyoto", "La Paz", "Lagos", "Lahore", "Libreville", "Lilongwe", "Lima", "Lisbon",
    "Ljubljana", "Lome", "London", "Los Angeles", "Luanda", "Lubumbashi", "Lusaka", "Luxembourg", "Macau",
    "Madrid", "Majuro", "Makassar", "Malabo", "Male", "Mamoudzou", "Managua", "Manama", "Manaus", "Manila",
    "Maputo", "Maracaibo", "Maracay", "Mariehamn", "Marigot", "Maseru", "Mashhad", "Mbabane", "Mecca",
    "Medan", "Medellin", "Medina", "Melbourne", "Mexico City", "Miami", "Minsk", "Mogadishu", "Monaco",
    "Monrovia", "Montevideo", "Montreal", "Moroni", "Moscow", "Mosul", "Multan", "Mumbai", "Munich",
    "Muscat", "N'Djamena", "Nagoya", "Nairobi", "Nanchong", "Nanjing", "Nassau", "Nay Pyi Taw", "New York",
    "Niamey", "Nicosia", "Nouakchott", "Noumea", "Novosibirsk", "Nuku'alofa", "Nur-Sultan", "Nuuk", "Oranjestad",
    "Osaka", "Oslo", "Ottawa", "Ouagadougou", "Pago Pago", "Palembang", "Palo Alto", "Panama", "Papeete",
    "Paramaribo", "Paris", "Perth", "Philadelphia", "Phnom Penh", "Phoenix", "Podgorica", "Port Louis",
    "Port Moresby", "Port of Spain", "Port-Vila", "Port-au-Prince", "Porto Alegre", "Porto-Novo", "Prague",
    "Praia", "Pretoria", "Pristina", "Puebla", "Pune", "Pyongyang", "Quebec", "Quito", "Rabat", "Rawalpindi",
    "Recife", "Reykjavik", "Riga", "Rio de Janeiro", "Riyadh", "Road Town", "Rome", "Roseau", "Saint George's",
    "Saint Helier", "Saint John's", "Saint Peter Port", "Saint Petersburg", "Saint-Denis", "Saint-Pierre",
    "Saipan", "Salvador", "San Antonio", "San Diego", "San Francisco", "San Jose", "San Juan", "San Marino",
    "San Salvador", "Sanaa", "Santa Cruz de la Sierra", "Santiago", "Santo Domingo", "Sao Paulo",
    "Sao Tome", "Sapporo", "Sarajevo", "Seattle", "Semarang", "Seoul", "Shanghai", "Sharjah", "Shenzhen",
    "Singapore", "Skopje", "Sofia", "South Tangerang", "Soweto", "Stockholm", "Sucre", "Surabaya", "Suva",
    "Sydney", "Tabriz", "Taipei", "Tallinn", "Tangerang", "Tarawa", "Tashkent", "Tbilisi", "Tegucigalpa",
    "Tehran", "Tel Aviv", "Thimphu", "Tianjin", "Tijuana", "Tirane", "Tokyo", "Toronto", "Torshavn", "Tripoli",
    "Tunis", "Ulaanbaatar", "Vaduz", "Valencia", "Valletta", "Vancouver", "Victoria", "Vienna", "Vientiane",
    "Vilnius", "Warsaw", "Washington", "Wellington", "Willemstad", "Windhoek", "Wuhan", "Xi'an", "Yamoussoukro",
    "Yangon", "Yaounde", "Yekaterinburg", "Yerevan", "Yokohama", "Zagreb"
]

major_cities_short = [
    "Tokyo",
    "New York",
    "London",
    "Paris",
    "Berlin",
    "Los Angeles",
    "Chicago",
    "Toronto",
    "Mexico City",
    "Sao Paulo",
    "Buenos Aires",
    "Rio de Janeiro",
    "Lima",
    "Bogota",
    "Madrid",
    "Rome",
    "Moscow",
    "Istanbul",
    "Cairo",
    "Dubai",
    "Tehran",
    "Delhi",
    "Mumbai",
    "Bangalore",
    "Kolkata",
    "Dhaka",
    "Karachi",
    "Lahore",
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Hong Kong",
    "Seoul",
    "Tokyo",
    "Osaka",
    "Bangkok",
    "Singapore",
    "Jakarta",
    "Manila",
    "Ho Chi Minh City",
    "Sydney",
    "Melbourne",
    "Johannesburg",
    "Cape Town",
    "Nairobi",
    "Lagos",
    "Kinshasa"
]

